language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"  
# command to install dependencies
install: pip install .
script: python tests/test_all_of_the_units.py
branches:
  only:
    - master