language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"  
# command to install dependencies
install:
   - pip install -r requirements.txt
   - python setup.py build_ext
   - python setup.py install
script: python topicmodel_tests/testsuite.py
branches:
  only:
    - master